### ISSUE TITLE
Library linking order on CC CLI in makefile not correct for gcc (Ubuntu 7.3.0-27ubuntu1~18.04)

### ISSUE THREAD

**Issue by clemera** [codemac/youinput#1]
I'm a total C noob, so maybe I'm missing something obvious. I'm on Ubuntu and installed
libx11-dev, libxi-dev but I get the following:

    gcc -lX11 -lXi youinput.o -o youinput
    youinput.o: In function `main':
    youinput.c:(.text.startup+0x157): undefined reference to `XOpenDisplay'
    youinput.c:(.text.startup+0x165): undefined reference to `XListInputDevices'
    youinput.c:(.text.startup+0x1ac): undefined reference to `XFreeDeviceList'
    youinput.c:(.text.startup+0x1b4): undefined reference to `XCloseDisplay'
    youinput.c:(.text.startup+0x1c3): undefined reference to `XFreeDeviceList'
    youinput.c:(.text.startup+0x1cb): undefined reference to `XCloseDisplay'
    collect2: error: ld returned 1 exit status

Any ideas what could be wrong or how I could fix this?

**Comment by clemera** [comment]
I had to move the linker flags to the end:

    gcc youinput.o -o youinput -lX11 -lXi

**Comment by codemac** [comment]
Are you typing this from the Makefile? It should just work.

**Comment by clemera** [comment]
It did not work until I changed the order, someone on irc suggested this because gcc is sometimes picky on this. I did this in the Makefile.

**Comment by codemac** [comment]
I have checked in a better order. Would love to know what version of GCC you're using, this makefile worked with:

gcc version 7.3.0 (Debian 7.3.0-5)

Ideally I'll make this a simple generic Makefile that supports as many compilers/linker versions as it can.

**Comment by clemera** [comment]
I use:

gcc (Ubuntu 7.3.0-27ubuntu1~18.04)

Strange that it did not work.
